server:
  port: 30000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: LTAI4G93tBLqh3Qdaq2DpDEg
      secret-key: Fdi8kI0k5K715gjgEG8UHCqTHqtHB1
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: shqilamall-file
