server:
  port: 30000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: shqilamall-file
