spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 122324
    url: jdbc:mysql://localhost:3306/shiqlamall_sms
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 55d78d3e-751d-41b4-9374-47b0ab2c95e7
  application:
    name: shiqlamall-coupon

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 7000
